cashCount/urls.py
from django.urls import path

from . import views
app_name = 'cashCount'

urlpatterns = [
    path('home/', views.cashMemo,name = 'cashMemo'),
    path('create/',views.createCashMemo,name="createCashMemo"),
    path('completed/',views.completedCashMemo,name="completedCashMemo"),
    path('FixBudget/',views.FixBudget,name="FixBudget"),
    path('show/<int:cash_pk>',views.showCashMemo,name="showCashMemo"),
    path('delete/<int:cash_pk>',views.deleteCashMemo,name="deleteCashMemo"),
    #path('update/<int:cash_pk>',views.updateBudget,name="updateBudget"),


]

todo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from todo_a import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('Tips/',views.tips,name="tips"),
    #AUTH
    path('signup/',views.signupUser,name="signupUser"),
    path('logout/',views.logoutuser,name="logoutuser"),
    path('login/',views.loginUser,name="loginUser"),
    #TODO
    path('currenttodo/',views.currenttodo,name="currenttodo"),
    path('completed/',views.completedtodo,name="completedtodo"),
    path('create/',views.createtodo,name="createtodo"),
    path('todo/<int:todo_pk>',views.viewtodo,name="viewtodo"),
    path('todo/<int:todo_pk>/complete',views.completetodo,name="completetodo"),
    path('todo/<int:todo_pk>/delete',views.deletetodo,name="deletetodo"),
    path('cashCount/', include('cashCount.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cashCount/models.py
from django.db import models

from django.contrib.auth.models import User

class CashMemo(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)
    cost = models.DecimalField(max_digits=20, decimal_places=2,default=0)
    created = models.DateTimeField(auto_now_add=True)
    taken = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class FixBudetModel(models.Model):
    budget = models.DecimalField(max_digits=20, decimal_places=2,default=0)
    userb = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.userb.username

cashCount/forms.py
from django.forms import ModelForm
from .models import CashMemo,FixBudetModel

class CashMemoForm(ModelForm):
    class Meta:
        model = CashMemo
        fields = ['title','memo','cost','taken']

class FixBudetForm(ModelForm):
    class Meta:
        model = FixBudetModel
        fields = ['budget']

cashCount/views.py
# Create your views here.


from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import CashMemoForm,FixBudetForm
from .models import CashMemo,FixBudetModel


@login_required
def cashMemo(request):
    return render(request,'cashCount/cashHome.html')


@login_required
def getBudget(request):
    cashBud = get_object_or_404(FixBudetModel,userb=request.user)
    try:
        return cashBud
    except ValueError:
        return None





@login_required
def createCashMemo(request):
        if request.method == 'GET':
            return render(request,'cashCount/createCashMemo.html',{ 'form':CashMemoForm()})
        else:
            try:
                form = CashMemoForm(request.POST)
                memo = form.save(commit=False)
                memo.user = request.user
                memo.save()
                #updateBudget(request,memo.id)
                return redirect('cashCount:completedCashMemo')
            except ValueError:
                return render(request,'cashCount/createCashMemo.html',{ 'form':CashMemoForm(),'error':'Bad Data'})


@login_required
def showCashMemo(request,cash_pk):
    cash = get_object_or_404(CashMemo,pk=cash_pk,user=request.user)
    cashBud = get_object_or_404(FixBudetModel,userb=request.user)
    if request.method == 'GET':
        form = CashMemoForm(instance=cash)
        return render(request,'cashCount/cashview.html',{'cash':cash,'form':form})
    else:
        try:
            form = CashMemoForm(request.POST, instance=cash)
            form.save()
            #updateBudget(request,cash_pk)
            return redirect('cashCount:completedCashMemo')
        except ValueError:
            return render(request,'cashCount/cashview.html',{'cash':cash,'form':form,'error':'Bad Data'})


@login_required
def completedCashMemo(request):
    cash = CashMemo.objects.filter(user=request.user).order_by('-created')
    alltaken = 0
    allgiven = 0
    for x in cash:
        if x.taken:
            alltaken += x.cost
        else:
            allgiven += x.cost
    return render(request,'cashCount/completedCashMemo.html',{'cash':cash,'alltaken':alltaken,'allgiven':allgiven})

@login_required
def deleteCashMemo(request,cash_pk):
    cash = get_object_or_404(CashMemo,pk=cash_pk,user=request.user)
    if request.method == 'POST':
        cash.delete()
        return redirect('cashCount:completedCashMemo')


@login_required
def FixBudget(request):
    if request.method == 'GET':
        cashBud = FixBudetModel.objects.all()
        for bud in cashBud:
            if bud.userb == request.user:
                cash = CashMemo.objects.filter(user=request.user).order_by('-created')
                alltaken = 0
                allgiven = 0
                for x in cash:
                    if x.taken:
                        alltaken += x.cost
                    else:
                        allgiven += x.cost
                bud.budget = bud.budget - alltaken + allgiven
                return render(request,'cashCount/fixBudget.html',{ 'form':FixBudetForm(),'cashBudget':bud})
        return render(request,'cashCount/fixBudget.html',{ 'form':FixBudetForm()})
    else:
        try:
            cashBud = FixBudetModel.objects.all()
            for bud in cashBud:
                if bud.userb == request.user:
                    form = FixBudetForm(request.POST,instance=bud)
                    form.save()
                    return redirect('cashCount:FixBudget')
            form = FixBudetForm(request.POST)
            newbudget = form.save(commit=False)
            newbudget.userb = request.user
            newbudget.save()
            return redirect('cashCount:FixBudget')

        except ValueError:
            return render(request,'cashCount/fixBudget.html',{ 'form':FixBudetForm(),'cashBud':cashBud,'error':'Max limit Crossed'})

cashCount/templates/cashCount/cashHome.html
{% extends 'cashCount/cbase.html' %}
{% block content %}
<br>
    <br>
    <br>
    <br>
    <br>
    <br>
<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">

                 <h1>Track Your Costing And Income. Woo!</h1>
            <p>Its difficult to track all the money given to someone or taken from someone. Its a simple app that tracks the costing <b>Memo</b>.Makes it really easy for you.<br>Lets fix your <b>Budget</b> </p>
        <a role="button" class="btn btn-primary btn-lg" href="{% url 'cashCount:FixBudget' %}">Start</a>
        </div>
    </div>
{% endblock %}

cashCount/templates/cashCount/cashview.html
{% extends 'cashCount/cbase.html' %}





{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Edit CashMemo</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title"><b>Title</b></label>
                <input type="text" name="title" class="form-control" id="title" value="{{ cash.title }}" required>
            </div>
            <div class="form-group">
                <label for="memo"><b>Memo</b></label>
                <textarea name="memo" rows="5" class="form-control" id="memo" >{{ cash.memo }}</textarea>
            </div>
            <div class="form-group">
                <label for="cost"><b>Amount</b></label><br>
                <input type="number" name="cost" class="form-control" id="cost" value="{{ cash.cost }}">
            </div>
            <div class="form-group form-check">
                <input type="checkbox" name="taken" class="form-check-input" id="important" {% if cash.taken %}checked{% endif %}>
                <label class="form-check-label" for="taken"><b>Taken or Given</b></label><br>
                <small>Tick if the amount <b>Taken</b> from you and  Untick if <b>Given</b> to you</small>
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-danger" onclick="$('#delete').click()">Delete</button>
        </form>
    </div>
</div>

<form style='display: none;' method="POST" action="{% url 'cashCount:deleteCashMemo' cash.id %}">
    {% csrf_token %}
    <button id="delete" type="submit">Delete</button>
</form>
{% endblock %}

cashCount/templates/cashCount/cbase.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "todo_a/custom.css" %}">

    <link href="https://fonts.googleapis.com/css2?family=Girassol&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static "todo_a/logo.png" %}">

    <title>TODO & CASHCOUNT</title>
  </head>
  <body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light bg-warning">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="{% static "todo_a/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nazmul's Logo">
      {% if user.is_authenticated %}
      <span>HI, <b>{{ user.username }}</b><small> Your CASHCOUNT</small></span>
      {% else %}
      <span>TODOS & CASHCOUNT</span>
      {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNav">
      {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cashCount:createCashMemo' %}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cashCount:completedCashMemo' %}">ShowMemos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cashCount:FixBudget' %}">Budget</a>
          </li>
        </ul>
      {% endif %}
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li>
            <a  class="nav-link" href="{% url 'currenttodo' %}" >TODOS</a>
          </li>
          <li class="nav-item">
            <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
            <form style='display: none;' method="POST" action="{% url 'logoutuser' %}">
              {% csrf_token %}
              <button id="signOutBtn" type="submit">Logout</button>
            </form>
          </li>

          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'signupUser' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'loginUser' %}">Login</a>
              </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tips' %}">Tips</a>
          </li>
      </ul>
    </div>

  </div>
</nav>
<div class="container">
  {% block content %}{% endblock %}
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

cashCount/templates/cashCount/check.html
{{ memo.cost }}
{{ cashBud.budget }}

cashCount/templates/cashCount/completedCashMemo.html
{% extends 'cashCount/cbase.html' %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-10">
        <h1>All CashMemos</h1>
        <h3>Total Taken Amount {{ alltaken }} Taka</h3>
        <h3>Total Given Amount {{ allgiven }} Taka</h3>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-10">
        <div class="list-group">
          {% if cash %}
            {% for x in cash %}
                <a href="{% url 'cashCount:showCashMemo' x.id %}" class="list-group-item list-group-item-action{% if x.taken %} list-group-item-danger{% endif %}">
                  <b>{{ x.title }}<b><br>
                  {% if x.taken %}<span><small>Amount Taken</small> {{ x.cost }} <small>Taka</small></span><br>
                  {% else %}<span><small>Amount Given</small> {{ x.cost }} <small>Taka</small></span><br>{% endif %}
                  {% if x.memo %}({{ x.memo|truncatechars:50 }}){% endif %}<br>
                  <small>Created in </small>{{ x.created|date:'M j Y H:i' }}
                </a>
            {% endfor %}
          {% else %}
            <div class="text-center">
                <h2>Looks like <b>Noone</b> borrowed from you and You dont have any cash history,<b> Nice work!!</b></h2>
            <br>
            <a role="button" class="btn btn-primary" href="{% url 'cashCount:createCashMemo' %}">New CashCount</a>
            </div>
          {% endif %}
        </div>
    </div>
</div>
{% endblock %}

cashCount/templates/cashCount/createCashMemo.html
{% extends 'cashCount/cbase.html' %}

{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>New CashMemo</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title"><b>Title</b></label><br>
                <small>'e.g <b>Shopping</b>'</small>
                <input type="text" name="title" class="form-control" id="title" required>
            </div>
            <div class="form-group">
                <label for="memo"><b>Memo</b></label><br>
                <small>'e.g <b>Pant, Shirt</b> etc or a description of the costing'</small>
                <textarea name="memo" class="form-control" id="memo" ></textarea>
            </div>
            <div class="form-group">
                <label for="cost"><b>Amount</b> <small>(in taka)</small></label><br>
                <input type="number" name="cost" class="form-control" id="cost">
            </div>
            <div class="form-group form-check">
                <input type="checkbox" name="taken" class="form-check-input" id="taken">
                <label class="form-check-label" for="taken"><b>Taken Or Given</b></label><br>
                <small>Tick if the amount <b>Taken</b> from you and keep Untick if <b>Given</b> to you</small>
            </div>
            <!--<div class="form-group form-check">
                <input type="checkbox" name="given" class="form-check-input" id="given">
                <label class="form-check-label" for="taken">Given To You</label>
            </div>-->
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>
{% endblock %}

cashCount/templates/cashCount/fixBudget.html
{% extends 'cashCount/cbase.html' %}
{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        {% if cashBudget %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <div class="col-md-10 text-center">
              <h1>Your Current Status:</h1>
                <button type="button" name="button" class="btn btn-primary btn-lg">{{ cashBudget.budget }}</button><br>
              </div>
                <div class="row justify-content-center mt-5">
                    <div class="col-md-8">
                        <h2>Update Budget</h2>
                    </div>
                </div>
                <label for="budget">Budget</label><br>
                <small><b>Create</b> a memo! The information given there will be uploaded in your <b>Budget</b>.<br></small>
                <small> <b>Taken</b> and <b>Given</b> amount still counted if not deleted the <b>Memo</b></small>
                <input type="number" name="budget" class="form-control" id="budget">
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        {% else %}
          <div class="row justify-content-center mt-5">
              <div class="col-md-8">
                  <h2>Fix Your Budget</h2>
              </div>
          </div>
          <form method="POST">
              {% csrf_token %}
              <div class="form-group">
                  <label for="budget">Budget</label>
                  <input type="number" name="budget" class="form-control" id="budget">
              </div>
              <button type="submit" class="btn btn-primary">Save</button>
          </form>
        {% endif %}

    </div>
</div>

{% endblock %}

cashCount/templates/cashCount/showbudget.html
{% extends 'cashCount/cbase.html' %}
{% block content %}
<br>
    <br>
    <br>
    <br>
    <br>
    <br>
<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">

                 <h1>Your Current Budget :</h1>
                 <h2>{{ error }}</h2>
                 {% if cashBud %}
                   <button type="button" name="button" class="btn btn-primary btn-lg">{{ cashBud.budget }}</button><br><br>
                   <a type="button" name="button" class="btn btn-primary btn-sm" action="#">UPDATE</a>
                 {% else %}
                   <div class="text-center">
                       <h2>Looks like you don't have a budget!! Lets Fix a Budget</h2>
                   <br>
                   <a role="button" class="btn btn-primary" href="{% url 'cashCount:FixBudget' %}">New Budget</a>
                   </div>
                   {% endif %}
        </div>
    </div>
{% endblock %}