cashCount/urls.py
from django.urls import path

from . import views
app_name = 'cashCount'

urlpatterns = [
    path('home/', views.cashMemo,name = 'cashMemo'),
    path('create/',views.createCashMemo,name="createCashMemo"),
    path('completed/',views.completedCashMemo,name="completedCashMemo"),
    path('FixBudget/',views.FixBudget,name="FixBudget"),
    path('show/<int:cash_pk>',views.showCashMemo,name="showCashMemo"),
    path('delete/<int:cash_pk>',views.deleteCashMemo,name="deleteCashMemo"),
    #path('update/<int:cash_pk>',views.updateBudget,name="updateBudget"),


]

todo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from todo_a import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('Tips/',views.tips,name="tips"),
    #AUTH
    path('signup/',views.signupUser,name="signupUser"),
    path('logout/',views.logoutuser,name="logoutuser"),
    path('login/',views.loginUser,name="loginUser"),
    #TODO
    path('currenttodo/',views.currenttodo,name="currenttodo"),
    path('completed/',views.completedtodo,name="completedtodo"),
    path('create/',views.createtodo,name="createtodo"),
    path('todo/<int:todo_pk>',views.viewtodo,name="viewtodo"),
    path('todo/<int:todo_pk>/complete',views.completetodo,name="completetodo"),
    path('todo/<int:todo_pk>/delete',views.deletetodo,name="deletetodo"),
    path('cashCount/', include('cashCount.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todo_a/models.py
from django.db import models
from django.contrib.auth.models import User

class TODO(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True,blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todo_a/forms.py
from django.forms import ModelForm
from .models import TODO

class TodoForm(ModelForm):
    class Meta:
        model = TODO
        fields = ['title','memo','important']

todo_a/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login,logout,authenticate
from .forms import TodoForm
from .models import TODO
from django.utils import timezone
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request,'todo_a/home.html')

def tips(request):
    return render(request,'todo_a/tips.html')


def signupUser(request):
    if request.method == 'GET':
        return render(request,'todo_a/signupUser.html',{ 'form': UserCreationForm()})
    else:
        if  request.POST['password1'] ==  request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'],password = request.POST['password1'])
                user.save()
                login(request,user)
                return redirect('currenttodo')
            except IntegrityError:
                return render(request,'todo_a/signupUser.html',{ 'form': UserCreationForm(),'error':'The username already taken, please  try again'})

        else:
            return render(request,'todo_a/signupUser.html',{ 'form': UserCreationForm(),'error':'The Password didnt match'})

def loginUser(request):
        if request.method == 'GET':
            return render(request,'todo_a/loginUser.html',{ 'form': AuthenticationForm()})
        else:
            user = authenticate(request,username=request.POST["username"],password=request.POST["password"])
            if user is None:
                return render(request,'todo_a/loginUser.html',{ 'form': AuthenticationForm(),'error':'username or password is wrong'})
            else:
                login(request,user)
                return redirect('currenttodo')

def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

@login_required
def createtodo(request):
        if request.method == 'GET':
            return render(request,'todo_a/createtodo.html',{ 'form':TodoForm()})
        else:
            try:
                form = TodoForm(request.POST)
                newtodo = form.save(commit=False)
                newtodo.user = request.user
                newtodo.save()
                return redirect('currenttodo')
            except ValueError:
                return render(request,'todo_a/createtodo.html',{ 'form':TodoForm(),'error':'Bad Data'})

@login_required
def currenttodo(request):
    todos = TODO.objects.filter(user=request.user,datecompleted__isnull=True)
    return render(request,'todo_a/currenttodo.html',{'todos':todos})

@login_required
def completedtodo(request):
    todos = TODO.objects.filter(user=request.user,datecompleted__isnull=False).order_by('-datecompleted')
    return render(request,'todo_a/completedtodo.html',{'todos':todos})






@login_required
def viewtodo(request,todo_pk):
    todo = get_object_or_404(TODO,pk=todo_pk,user=request.user)
    if request.method == 'GET':
        form = TodoForm(instance=todo)
        return render(request,'todo_a/todoview.html',{'todo':todo,'form':form})
    else:
        try:
            form = TodoForm(request.POST, instance=todo)
            form.save()
            return redirect('currenttodo')
        except ValueError:
            return render(request,'todo_a/todoview.html',{'todo':todo,'form':form,'error':'Bad Data'})

@login_required
def completetodo(request,todo_pk):
    todo = get_object_or_404(TODO,pk=todo_pk,user=request.user)
    if request.method == 'POST':
        todo.datecompleted = timezone.now()
        todo.save()
        return redirect('currenttodo')

@login_required
def deletetodo(request,todo_pk):
    todo = get_object_or_404(TODO,pk=todo_pk,user=request.user)
    if request.method == 'POST':
        todo.delete()
        return redirect('currenttodo')

todo_a/templates/todo_a/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "todo_a/custom.css" %}">

    <link href="https://fonts.googleapis.com/css2?family=Girassol&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static "todo_a/logo.png" %}">

    <title>TODO & CASHCOUNT</title>
  </head>
  <body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light bg-warning">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">
      <img src="{% static "todo_a/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nazmul's Logo">
      {% if user.is_authenticated %}
      <span>HI, <b>{{ user.username }}</b><small> Your TODOS</small></span>
      {% else %}
      <span>TODOS & CASHCOUNT</span>
      {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNav">
      {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'createtodo' %}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'currenttodo' %}">Current</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'completedtodo' %}">Completed</a>
          </li>
        </ul>
      {% endif %}
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-link" href="{% url 'cashCount:cashMemo' %}">CashCount</a>
          </li>
          <li class="nav-item">
            <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
            <form style='display: none;' method="POST" action="{% url 'logoutuser' %}">
              {% csrf_token %}
              <button id="signOutBtn" type="submit">Logout</button>
            </form>
          </li>

          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'signupUser' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'loginUser' %}">Login</a>
              </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tips' %}">Tips</a>
          </li>
      </ul>
    </div>

  </div>
</nav>
<div class="container">
  {% block content %}{% endblock %}
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

todo_a/templates/todo_a/completedtodo.html
{% extends 'todo_a/base.html' %}
{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-10">
        <h1>Completed Todos</h1>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-10">
        <div class="list-group">
            {% for todo in todos %}
                <a href="{% url 'viewtodo' todo.id %}" class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}"><b>{{ todo.title }}</b> - Completed In <b>{{ todo.datecompleted|date:'M j Y H:i' }}</b></a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todo_a/templates/todo_a/createtodo.html
{% extends 'todo_a/base.html' %}
{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>New Todo</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title"><b>Title</b></label><br>
                <small>'e.g <b>Morning Exercise</b>'<small>
                <input type="text" name="title" class="form-control" id="title" required>
            </div>
            <div class="form-group">
                <label for="memo"><b>Memo</b></label><br>
                <small>'Description of the event.'</small>
                <textarea name="memo" class="form-control" id="memo" ></textarea>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" name="important" class="form-check-input" id="important">
                <label class="form-check-label" for="important"><b>Important</b></label><br>
                <small>If this is your important task then tick the option and it will be highlighted in your list</small>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

todo_a/templates/todo_a/currenttodo.html
{% extends 'todo_a/base.html' %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            {% if todos %}
                 <h1>{{ todos.count }} Current Todo{{ todos.count|pluralize }}</h1>
            {% else %}
                           <h1>Current Todos</h1>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
        {% if todos %}
            <div class="list-group">
                {% for todo in todos %}
                    <a href="{% url 'viewtodo' todo.id %}" class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}"><b>{{ todo.title }}</b>{% if todo.memo %} - {{ todo.memo|truncatechars:30 }}{% endif %}</a>
                {% endfor %}
            </div>
        {% else %}
            <div class="text-center">
                <h2>Looks like you don't have any todos! Nice work.</h2>
            <br>
            <a role="button" class="btn btn-primary" href="{% url 'createtodo' %}">New Todo</a>
            </div>
        {% endif %}
        </div>
    </div>

{% endblock %}

todo_a/templates/todo_a/home.html
{% extends 'todo_a/base.html' %}
{% block content %}
{% if user.is_authenticated %}

<br>
    <br>
    <br>
    <br>
<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">

                 <h1>Remember Your Event and Track Your Cash!</h1>
                 <p>Hey You Are <b>LoogedIn</b> </p>
        <a role="button" class="btn btn-success btn-lg" href="{% url 'currenttodo' %}">See TODOS</a><br><br>
        <a role="button" class="btn btn-success btn-lg" href="{% url 'cashCount:completedCashMemo' %}">See CashCount</a>
        </div>
    </div>

{% else %}
<br>
    <br>
    <br>
    <br>
<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">

                 <h1>Remember Your Event and Track Your Cash!</h1>
            <p>Life is fun. But life is also busy. There's a million different things you could be doing. But what matters is <u>what</u> you do. I created <b><i>Todos & CashCount</i></b> to help you make things easier for you. Track your money <b>Borrowed</b> from someone or <b>Lend</b> to someone.  Your new organized life awaits.</p>
        <a role="button" class="btn btn-primary btn-lg" href="{% url 'signupUser' %}">Start</a>
        </div>
    </div>

{% endif %}
<br>
<br>
<br>
<a href="https://nazmul.pythonanywhere.com/" target = "blank"><p style="text-align:center">About Developer</p></a>
{% endblock %}

todo_a/templates/todo_a/loginUser.html
{% extends 'todo_a/base.html' %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Login</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <hr>
            <div class="text-center">
                Need an account? <a href="{% url 'signupUser' %}">Sign Up here</a>
            </div>
        </div>
    </div>
{% endblock %}

todo_a/templates/todo_a/signupUser.html
{% extends 'todo_a/base.html' %}
{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Sign Up</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
            </div>
            <div class="form-group">
                <label for="password1">Password</label>
                <input type="password" name="password1" class="form-control" id="password1">
            </div>
            <div class="form-group">
                <label for="password2">Confirm Password</label>
                <input type="password" name="password2" class="form-control" id="password2">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
        <hr>
        <div class="text-center">
            Do you already have an account? <a href="{% url 'loginUser' %}">Login here</a>
        </div>
    </div>
</div>
{% endblock %}

todo_a/templates/todo_a/tips.html
{% extends 'todo_a/base.html' %}
{% block content %}
<div class="container">
  <h1>Here is some tips for using this application</h1>
  <ol type="A">
    <li>
      Click your name and it will take you to the homepage.
    </li>
    <li>
      You can do two things:
      <ol type="1">
        <li> Make and track your event list. </li>
        <li>Fix your budget and track the money, "spend or earned"</li>
      </ol>
    </li>
    <li>In the todo app you have 3 options:
      <ol type="1">
        <li><b>Create</b>    : You can create a new event with title, memo and you can mark this event as important</li>
        <li><b>Current</b>   : You can see your current todos. Important ones will be highlighted.
                        By clicking an event you can edit, mark as completed and delete the event</li>
        <li><b>Completed</b> : You can see the completed events and the time when completed then you can delete the event.</li>
      </ol>
    </li>
    <li>
      In the CashCount app you have 3 options:
      <ol type="1">
        <li><b>Create</b> :  You can create a new Cash Memo with title, memo, amount and mark if the money
           taken from you or given to you</li>
        <li><b>ShowMemos</b> : You can see your current memos. Also you can see total money taken from you or given to you.
          In the memo list you also can see the time when that memo was created. By clicking an event you can edit and delete the Memo.
        </li>
        <li><b>Budget</b> : Now this is where your total budget is fixed and updated whenever a memo is created.</li>
      </ol>
      <li>You can interchange between these two application by clicking <b>TODOS</b> or <b>CashCount</b> button.
  </ol>
</div>
{% endblock %}

todo_a/templates/todo_a/todoview.html
{% extends 'todo_a/base.html' %}
{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Update Todo</h2>
    </div>
</div>
<div class="row justify-content-center mt-4">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="title"><b>Title</b></label>
                <input type="text" name="title" class="form-control" id="title" value="{{ todo.title }}" required>
            </div>
            <div class="form-group">
                <label for="memo"><b>Memo</b></label>
                <textarea name="memo" rows="5" class="form-control" id="memo" >{{ todo.memo }}</textarea>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" name="important" class="form-check-input" id="important" {% if todo.important %}checked{% endif %}>
                <label class="form-check-label" for="important"><b>Important</b></label><br>
                <small>If this is your important task then tick the option and it will be highlighted in your list</small>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-success" onclick="$('#complete').click()">Complete</button>
            <button type="button" class="btn btn-danger" onclick="$('#delete').click()">Delete</button>
        </form>
    </div>
</div>
{% if todo.datecompleted is None %}
    <form style='display: none;' method="POST" action="{% url 'completetodo' todo.id %}">
        {% csrf_token %}
        <button id="complete" type="submit">Complete</button>
    </form>
{% endif %}
<form style='display: none;' method="POST" action="{% url 'deletetodo' todo.id %}">
    {% csrf_token %}
    <button id="delete" type="submit">Delete</button>
</form>

{% endblock %}